### ISSUE TITLE
Chapter 4 transaltion

### ISSUE THREAD

**Issue by bruunoromero** [ygorlazaro/js-stack-from-scratch#1]
Can I start translating chapter 4?

**Comment by ygorlazaro** [comment]
Sure! I'm at the chapter 1

**Comment by ygorlazaro** [comment]
Chapter 1 done. b3210cdee549dd4da95027350d11776de78f9610

**Comment by bruunoromero** [comment]
Ok man, chapter 4 is almost done.

**Comment by ygorlazaro** [comment]
Merged  6af3f6447dc831d81f59e45e2e44ba88d7f0460d
